tasks:
  throughput_regression:
    estimator: xgboost
    params: {max_depth: 6, n_estimators: 400, learning_rate: 0.05}
    metric: rmse
  latency_forecasting:
    estimator: lstm
    horizon: 12
    metric: mae
  anomaly_detection:
    estimator: isolation_forest
    params: {n_estimators: 200, contamination: 0.02}
    metric: pr_auc
  performance_classification:
    estimator: xgboost
    params: {max_depth: 5, n_estimators: 300, learning_rate: 0.05}
    metric: f1_macro
registry:
  model_name_prefix: "thesis_netmon"
